### ISSUE TITLE
patch findlibs dependency

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/python-Magics-rpm#1]
since version 1.5.7 ECMWF introduced a new dependency called findlibs to find libeccodes.so easier on non-linux platforms but it's not packaged.

On fedora python-eccodes package findlibs has been patched out (see https://github.com/ARPA-SIMC/python-eccodes-rpm/blob/master/python-eccodes-disable-findlibs.patch), it should be patched out on python-Magics too.

**Comment by edigiacomo** [comment]
I wrote the patch and bumped the release version. The package works on my machine®, I wait for moncic-ci build to close the issue.

**Comment by edigiacomo** [comment]
Something went wrong (QED): the monci-ci build was successful, but the Copr build failed while building the SRPM.
